variables:
  solution: Umbraco.StorageProviders.sln
  buildConfiguration: Release
  NUGET_PACKAGES: ''
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

stages:
  - stage: Artifacts
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - task: Cache@2
            displayName: Cache NuGet packages
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
              path: '$(NUGET_PACKAGES)'
              cacheHitVar: 'CACHE_RESTORED'

          - script: dotnet restore $(solution) --locked-mode
            displayName: Restore NuGet packages
            condition: ne(variables.CACHE_RESTORED, true)

          - script: dotnet build $(solution) -c $(buildConfiguration) -p:ContinuousIntegrationBuild=true --no-restore
            displayName: Build

          - script: dotnet pack $(solution) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-restore --no-build
            displayName: Pack

          - task: PublishBuildArtifacts@1
            displayName: Publish NuGet packages
            inputs:
                ArtifactName: nupkg
